server {
    listen 8080;
    server_name whatsapp.agsatu.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name whatsapp.agsatu.id;

    ssl_certificate /etc/letsencrypt/live/whatsapp.agsatu.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/whatsapp.agsatu.id/privkey.pem;

    root /var/www/gowa/fe/dist;
    index index.html;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://whatsapp-backend-prod:3000/;  # nama container + port internal
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Optional: timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Static assets caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|json)$ {
        root /var/www/gowa/fe/dist;
        access_log off;
        expires max;
    }

   
}
